45 sqlalchemy
megalis-bretagne/MegActe pull request #46
Opened 2024-05-17 15:00 UTC by BoussairiIkram

CRUD DONE

2024-05-17 15:14 UTC, syji35 requested changes
Renommer le champ id_user en id_pastell pour être plus clair.

2024-05-17 15:14 UTC, syji35 commented on back/app/models/users.py
> +    id_user = Column(Integer, unique=True)
Renommer en id_pastell

2024-05-17 15:14 UTC, syji35 commented on back/app/routers/users.py
> +    db_user = db.query(UserPastell).filter(UserPastell.id == user_id).first()
Je t'expliquerai plus tard, mais sur les opérations de Delete ou Update, il ne faut pas passer par les ID directement.

Mais plutot utiliser des Random UUID. 
Ca évite qu'un attaquant puisse supprimer des utilisateurs avec des id "classique" : 1,2,3 etc..

2024-05-17 15:14 UTC, syji35 commented on back/app/models/users.py
> +    # TO COMPLETE
Retirer le TO Complete

2024-05-21 07:53 UTC, BoussairiIkram commented on back/app/models/users.py
> +    id_user = Column(Integer, unique=True)
DONE

2024-05-21 07:53 UTC, BoussairiIkram commented on back/app/models/users.py
> +    # TO COMPLETE
DONE

2024-05-21 08:02 UTC, syji35 approved these changes

2024-05-21 08:02 UTC, merged