45 sqlalchemy
megalis-bretagne/MegActe pull request #48
Opened 2024-05-22 12:06 UTC by BoussairiIkram

Envoyer le mot de passe non chiffré à PASTELL -> DONE

2024-05-22 13:43 UTC, syji35 requested changes
Globalement, 
Revoir la gestion des Exceptions.
Ne jamais catcher des "Exceptions".
Passer par des handlers d'erreur au lieux de faire du try/ctach

2024-05-22 13:43 UTC, syji35 commented on back/app/models/users.py
>      # id_public = Column(UUID(as_uuid=True), unique=True, default=uuid.uuid4)
Supprimer le #id _public en commentaire

2024-05-22 13:43 UTC, syji35 commented on back/app/routers/users.py
> +    try:
il faudrait plutôt faire des handler pour catcher les exceptions : 

https://fastapi.tiangolo.com/tutorial/handling-errors/

2024-05-22 13:43 UTC, syji35 commented on back/app/routers/users.py
> +    except Exception as e:
Ne jamais catché des Exception, mais des exceptions spécifique

2024-05-22 13:43 UTC, syji35 commented on back/app/routers/users.py
> +        except Exception as e:
Idem, catch exception sur handler

2024-05-22 13:43 UTC, syji35 commented on back/app/services/user_service.py
> +        raise Exception(f"Failed to update password in Pastell: {response.text}")
Ne pas retourne le response.text de pastell directement.
Peux être retourner directement le code HTTP et la réponse de pastell directement.

2024-05-23 09:20 UTC, BoussairiIkram commented on back/app/models/users.py
>      # id_public = Column(UUID(as_uuid=True), unique=True, default=uuid.uuid4)
DONE

2024-05-23 09:21 UTC, BoussairiIkram commented on back/app/routers/users.py
> +    try:
Done, j'ai utilisé custom exception handlers.

2024-05-23 09:26 UTC, BoussairiIkram commented on back/app/routers/users.py
> +    except Exception as e:
Bien compris.

2024-05-23 09:40 UTC, syji35 requested changes

2024-05-23 09:40 UTC, syji35 commented on back/app/exceptions/custom_exceptions.py
> +    def __init__(self, status_code: int, detail: str):
Ajouter des commentaires

2024-05-23 13:28 UTC, syji35 approved these changes

2024-05-23 13:28 UTC, syji35 approved these changes

2024-05-23 13:29 UTC, syji35 approved these changes

2024-05-23 13:29 UTC, merged