35 UI dashboard megacte
megalis-bretagne/MegActe pull request #64
Opened 2024-05-31 11:35 UTC by BoussairiIkram

2024-05-31 13:53 UTC, syji35 requested changes

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/navbar/navbar.component.html
> +                                <a class="fr-btn" href="" (click)="logout($event)">
une balise <a> sert à renvoyer vers une page internet.
Si tu utilises le click, c'est un bouton qu'il faut.

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/navbar/navbar.component.html
> +                                <a class="fr-btn" routerLink="/user-profile">
regarde le RGAA, je pense qu'il manque des choses ici
: https://accessibilite.numerique.gouv.fr/methode/glossaire/#lien

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/navbar/navbar.component.ts
> +        console.error('Error fetching user context', error);
Il y a un logger dans le projet 
Il faut plutot utiliser ca : https://www.npmjs.com/package/ngx-logger

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/navbar/navbar.component.ts
> +    event.preventDefault();
Pas utile si bouton

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/user-profile/user-profile.component.html
> +        <p class="display-4"> Bonjour {{ userContext.user_info.prenom }}</p>
attention au espace.

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/user-profile/user-profile.component.html
> +                        <span aria-hidden="true">&raquo;</span>
pourquoi ca ?

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/user-profile/user-profile.component.html
> +                    <a class="page-link" href="#" aria-label="Next" (click)="changePage(currentPage + 1, $event)">
le aria-label doit être en Francais

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/user-profile/user-profile.component.html
> +        <table class="table table-striped table-hover fr-text--sm">
A remplacer par un composant Angular Material plus tard

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/user-profile/user-profile.component.html
> +            <h4>Entités : </h4>
Si l'utilisateur a une seule entité => afficher "Entité". Sinon Entités

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/services/keycloakServices/auth.service.ts
> +      console.log('Déconnexion réussie');
Logger

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/services/keycloakServices/auth.service.ts
> +      console.error('Erreur lors de la déconnexion', err);
Logger

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/services/userServices/user.service.ts
> +  getUserContext(): Observable<UserContext> {
Pour ajouter le token, ca peut être automatiquement par un HttpInterceptor.

Sinon, tu vas copier / coller ce code pour toutes les requêtes.

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/user-profile/user-profile.component.html
> +        <p class="lead">Bienvenue sur Megacte, Ceci est tes informations personnelles</p>
<p class="lead">Bienvenue sur Megacte.</p>

2024-05-31 13:53 UTC, syji35 commented on web-app/src/app/components/user-profile/user-profile.component.html
Le composant qui liste les entités de l'utilisateur sera fait avec un composant type Angular Material (qui gère la pagination de base etc...)
Dans un premier temps, tu peux juste afficher l'entité de base de l'utilisateur.
Si entité de base (id_e) = 0, alors tu affiches "utilisateur globale"
Sinon, tu affiches le nom de l'entité principal

2024-05-31 14:00 UTC, syji35 commented on web-app/src/app/components/user-profile/user-profile.component.html
> +        <p class="display-4"> Bonjour {{ userContext.user_info.prenom }}</p>
A vérifier si la balise <p> prend en compte l'espace du début

2024-06-03 08:22 UTC, BoussairiIkram commented on web-app/src/app/components/user-profile/user-profile.component.html
> +        <p class="display-4"> Bonjour {{ userContext.user_info.prenom }}</p>
Les espaces et les retours à la ligne dans la balise <p> ne sont pas pris en considération par le navigateur  : https://www.w3schools.com/html/html_paragraphs.asp
![Cap](https://github.com/megalis-bretagne/MegActe/assets/98105656/da1b7ee8-6038-4548-b3d9-24ee6e438694)

2024-06-03 12:58 UTC, syji35 approved these changes

2024-06-03 13:01 UTC, merged